services:
  - type: web
    name: zenflow
    runtime: node
    plan: free
    autoDeploy: true
    buildCommand: npm install --include=dev && npm --prefix server install && npm run build
    startCommand: NODE_ENV=production node server/index.js
    envVars:
      - key: ZENFLOW_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
